---
version: "2.0"

services:
  autopilot:
    image: thilakshriyan/akash-autopilot:latest@sha256:c9f0db198ff30204d36af1730bc6aba17f38ef618720d5cc09326547f3fe85cf
    
    env:
      # Akash Console API credentials
      - CONSOLE_API_KEY=ac.sk.production.211dad6023cd3bb9ce752b4602893bfb01fda4d7d8335ed925ff924bbdd17c17
      - CONSOLE_API_BASE_URL=https://console-api.akash.network
      
      # AkashML credentials
      - AKASHML_API_KEY=akml-yluUEjWbDvSVerKCXZkBYhzUPlKfzDZN
      - AKASHML_BASE_URL=https://api.akashml.com/v1
      - AKASHML_MODEL=meta-llama/Llama-3.3-70B-Instruct
      
      # Agent configuration
      - LOOP_INTERVAL=120
      - DB_PATH=/data/autopilot.db
      - DEMO_MODE=true
      
      # Policy guardrails
      - MAX_ACTIONS_PER_HOUR=10
      - MAX_ACTIONS_PER_DAY=50
      - SCALE_COOLDOWN_SECONDS=3600
      - REDEPLOY_COOLDOWN_SECONDS=7200
      - CLAIM_REWARDS_COOLDOWN_SECONDS=86400
      - REDELEGATE_COOLDOWN_SECONDS=604800
      
      # Wallet / Treasury (leave empty for mock mode)
      - WALLET_MNEMONIC=""
      - CHAIN_ID=testnet-8
      - RPC_ENDPOINT=https://testnetrpc.akashnet.net:443
      - MIN_BALANCE_UAKT=5000000
      - REWARD_CLAIM_THRESHOLD_UAKT=1000000
      
      # Logging
      - LOG_LEVEL=INFO
    
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
    
    # Persistent storage configuration
    params:
      storage:
        data:
          mount: /data
          readOnly: false

profiles:
  compute:
    autopilot:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          # Ephemeral storage for OS and logs
          - size: 256Mi
          # Persistent storage for database
          - name: data
            size: 1Gi
            attributes:
              persistent: true
              class: beta3
  
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        autopilot:
          denom: uakt
          amount: 10000

deployment:
  autopilot:
    dcloud:
      profile: autopilot
      count: 1
